// Standardlisten für die Auslosung. Auf der Seite unter "Listen bearbeiten" änderbar.
// Haribo und die Fitness-Bubble fehlen absichtlich: Sie bilden das Musterbeispiel (js/muster.js).
window.RR_DATA = {
  brands: [
    "LEGO | Kinder & Familien | Spielwaren",
    "Red Bull | Junge Erwachsene, Extremsport | Energydrinks",
    "Nivea | Breite Masse, Familien | Körperpflege",
    "Milka | Familien & Genießer | Süßwaren",
    "Jägermeister | Feiernde 18–35 | Spirituosen",
    "Playmobil | Kinder 4–10 Jahre | Spielwaren",
    "Rügenwalder Mühle | Familien & Flexitarier | Lebensmittel",
    "Dr. Oetker | Hobbybäcker:innen & Familien | Lebensmittel",
    "Capri-Sun | Schulkinder & Eltern | Getränke",
    "Werther's Original | Großeltern & Senior:innen | Süßwaren",
    "HiPP | Eltern von Babys | Babynahrung",
    "Tchibo | Kaffeetrinkende 40+ | Kaffee & Handel",
    "Deutsche Bahn | Pendelnde & Geschäftsreisende | Mobilität",
    "Rotkäppchen | Erwachsene, festliche Anlässe | Sekt",
    "Weber | Grillfans 30+ | Grills",
    "Mercedes-Benz | Gutverdienende 45+ | Automobil",
    "Ritter Sport | Breite Masse | Süßwaren",
    "Pampers | Eltern von Babys | Hygieneartikel",
    "Nintendo | Familien & Casual Gamer | Videospiele",
    "Duden | Schule, Büro & Sprachprofis | Verlag",
    "STABILO | Schüler:innen & Studierende | Schreibwaren",
    "Tupperware | Haushalte & Familien 40+ | Haushaltswaren",
    "Miele | Anspruchsvolle Haushalte 40+ | Hausgeräte",
    "Fisherman's Friend | Erwachsene mit Halskratzen | Pastillen",
    "Maggi | Familien, schnelle Küche | Lebensmittel",
    "Jack Wolfskin | Wandernde & Outdoor-Fans 40+ | Bekleidung",
    "ADAC | Autofahrer:innen | Mobilitätsclub",
    "Ravensburger | Familien & Puzzle-Fans | Spiele",
    "Kärcher | Hausbesitzer:innen & Gewerbe | Reinigungsgeräte",
    "Thermomix | Familien & Kochbegeisterte | Küchengeräte",
    "Club-Mate | Hacker, Kreative & Studierende | Getränke",
    "Sparkasse | Privatkundschaft, ältere Generation | Finanzen",
    "IKEA | Junge Familien & Erstausstatter | Möbel",
    "Lufthansa | Geschäftsreisende | Luftfahrt",
    "Barbie | Kinder 3–9 Jahre | Spielwaren"
  ].join("\n"),

  targets: [
    "Gamer & E-Sport | Lange Sessions, Twitch, Discord, Fokus",
    "Senior:innen 70+ | Gesundheit, Selbstständigkeit, Enkel, Print & TV",
    "Gen Z auf TikTok | Trends, Ironie, Authentizität, kurze Videos",
    "Luxus-Segment | Exklusivität, Status, hohe Zahlungsbereitschaft",
    "Vegane Community | Tierwohl, Nachhaltigkeit, klare Inhaltsstoffe",
    "Studierende | Knappes Budget, WG-Leben, Prüfungsstress",
    "Eltern von Kleinkindern | Sicherheit, Zeitmangel, wenig Schlaf",
    "Outdoor & Vanlife | Natur, Robustheit, Unabhängigkeit",
    "Hunde- & Katzenhalter:innen | Haustier als Familienmitglied",
    "B2B: Büros & Unternehmen | Einkauf, Effizienz, Großmengen",
    "LOHAS | Lifestyle of Health and Sustainability, kaufkräftig",
    "Handwerk & Baustelle | Profis, Robustheit, früher Arbeitsbeginn",
    "Pflege & Schichtarbeit | Nachtdienste, wenig Zeit, Energiebedarf",
    "Festival-Crowd | Sommer, Camping, Party, Gemeinschaft",
    "Digital Nomads | Remote Work, Reisen, Minimalismus",
    "Yoga & Achtsamkeit | Balance, Ruhe, Spiritualität",
    "Anime- & K-Pop-Fans | Fandom, Sammelleidenschaft, Community",
    "Landwirtschaft | Tradition, Wetter, Technik auf dem Hof",
    "Content Creator | Reichweite, Ästhetik, Kooperationen",
    "Motorrad-Szene | Freiheit, Technik, Biker-Treffs",
    "Hochzeitspaare | Einmaliger Anlass, Emotionen, Budgetplanung",
    "Expats & Neu-Zugezogene | Orientierung, Heimweh, Mehrsprachigkeit",
    "Gastronomie & Hotellerie | B2B, Großküchen, Gästeerlebnis",
    "Kliniken & Arztpraxen | B2B, Hygiene, Zertifizierung, Beschaffung",
    "Start-up-Gründer:innen | Hustle-Kultur, LinkedIn, wenig Zeit",
    "Smart-Home-Fans | Technikbegeisterung, Vernetzung, Early Adopter",
    "Singles 50+ | Dating, Neuanfang, Reisen"
  ].join("\n"),

  // Kombinationen, die zu nah an der heutigen Zielgruppe liegen oder nicht passen
  // (z. B. Alkohol für sehr junge Zielgruppen). Diese werden nicht ausgelost.
  avoid: {
    "Red Bull": ["Gamer & E-Sport", "Festival-Crowd", "Studierende"],
    "Club-Mate": ["Studierende", "Gamer & E-Sport"],
    "Jack Wolfskin": ["Outdoor & Vanlife"],
    "HiPP": ["Eltern von Kleinkindern"],
    "Pampers": ["Eltern von Kleinkindern"],
    "Werther's Original": ["Senior:innen 70+"],
    "Sparkasse": ["Senior:innen 70+"],
    "Mercedes-Benz": ["Luxus-Segment"],
    "Kärcher": ["Handwerk & Baustelle"],
    "Rügenwalder Mühle": ["Vegane Community"],
    "Nintendo": ["Gamer & E-Sport"],
    "STABILO": ["Studierende"],
    "Duden": ["Studierende"],
    "IKEA": ["Studierende"],
    "ADAC": ["Motorrad-Szene"],
    "Lufthansa": ["B2B: Büros & Unternehmen"],
    "Jägermeister": ["Festival-Crowd", "Gen Z auf TikTok", "Kliniken & Arztpraxen"],
    "Rotkäppchen": ["Hochzeitspaare", "Gen Z auf TikTok", "Kliniken & Arztpraxen"]
  }
};
